### ISSUE TITLE
Error screen when uploading large files

### ISSUE THREAD

**Issue by fermatijoe** [deeepaaa/librebook#1]
I tried to upload a 150MB pdf book, but the page crashed with [this](http://i.imgur.com/pLfRlVl.png) error (win 10 / chrome).

Abufinzio saluta.

**Comment by alex-dp** [comment]
150MB is way over the limit specified in the FAQ page. In case the book was not scanned, you could try converting it to epub.

http timed out before the upload could be completed.

Also, I suggest the use of free software rather than "win 10 / chrome"
